"""add_tenant_settings_and_extended_fields

Revision ID: d8322aee9083
Revises: cef10122d5e1
Create Date: 2026-07-24 19:58:53.420519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8322aee9083'
down_revision: Union[str, None] = 'cef10122d5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_visitors', sa.Integer(), nullable=False),
    sa.Column('allowed_login_methods', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=True)
    op.add_column('tenants', sa.Column('code', sa.String(length=20), nullable=False))
    op.add_column('tenants', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.alter_column('tenants', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED', 'ARCHIVED', name='tenant_status'),
               existing_nullable=False)
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=True)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_foreign_key(None, 'tenants', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tenants', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tenants', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED', 'ARCHIVED', name='tenant_status'),
               type_=mysql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED'),
               existing_nullable=False)
    op.drop_column('tenants', 'deleted_by_id')
    op.drop_column('tenants', 'updated_by_id')
    op.drop_column('tenants', 'created_by_id')
    op.drop_column('tenants', 'domain')
    op.drop_column('tenants', 'slug')
    op.drop_column('tenants', 'code')
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
