class AuditActions:
    """
    Constants for system audit log action strings.
    """
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    USER_RESTORED = "USER_RESTORED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET = "PASSWORD_RESET"
    PROFILE_UPDATED = "PROFILE_UPDATED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    TOKEN_REFRESH = "TOKEN_REFRESH"

    # Tenant Management Audit Actions
    TENANT_CREATED = "TENANT_CREATED"
    TENANT_UPDATED = "TENANT_UPDATED"
    TENANT_SUSPENDED = "TENANT_SUSPENDED"
    TENANT_ACTIVATED = "TENANT_ACTIVATED"
    TENANT_DELETED = "TENANT_DELETED"
    TENANT_RESTORED = "TENANT_RESTORED"

    # Visitor Management Audit Actions
    VISITOR_CREATED = "VISITOR_CREATED"
    VISITOR_UPDATED = "VISITOR_UPDATED"
    VISITOR_VERIFIED = "VISITOR_VERIFIED"
    VISITOR_BLACKLISTED = "VISITOR_BLACKLISTED"
    VISITOR_BLACKLIST_REMOVED = "VISITOR_BLACKLIST_REMOVED"
    VISITOR_RESTORED = "VISITOR_RESTORED"
    VISITOR_DELETED = "VISITOR_DELETED"
    VISITOR_ACTIVATED = "VISITOR_ACTIVATED"
    VISITOR_DEACTIVATED = "VISITOR_DEACTIVATED"

    # Visit Request Audit Actions
    VISIT_REQUEST_CREATED = "VISIT_REQUEST_CREATED"
    VISIT_REQUEST_UPDATED = "VISIT_REQUEST_UPDATED"
    VISIT_REQUEST_APPROVED = "VISIT_REQUEST_APPROVED"
    VISIT_REQUEST_REJECTED = "VISIT_REQUEST_REJECTED"
    VISIT_REQUEST_CANCELLED = "VISIT_REQUEST_CANCELLED"
    VISIT_REQUEST_RESTORED = "VISIT_REQUEST_RESTORED"
    VISIT_REQUEST_DELETED = "VISIT_REQUEST_DELETED"

    # Visitor Pass & QR Audit Actions
    PASS_GENERATED = "PASS_GENERATED"
    PASS_UPDATED = "PASS_UPDATED"
    PASS_DELETED = "PASS_DELETED"
    PASS_RESTORED = "PASS_RESTORED"
    PASS_REVOKED = "PASS_REVOKED"
    PASS_EXPIRED = "PASS_EXPIRED"
    QR_REGENERATED = "QR_REGENERATED"
    # Host Availability Audit Actions
    AVAILABILITY_CREATED = "AVAILABILITY_CREATED"
    AVAILABILITY_UPDATED = "AVAILABILITY_UPDATED"
    AVAILABILITY_DELETED = "AVAILABILITY_DELETED"
    AVAILABILITY_EXCEPTION_CREATED = "AVAILABILITY_EXCEPTION_CREATED"
    AVAILABILITY_EXCEPTION_DELETED = "AVAILABILITY_EXCEPTION_DELETED"

    # Approval Workflow Audit Actions
    APPROVAL_CREATED = "APPROVAL_CREATED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DELEGATED = "DELEGATED"
    ESCALATED = "ESCALATED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"

    # Notification Management Audit Actions
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    NOTIFICATION_READ = "NOTIFICATION_READ"
    TEMPLATE_CREATED = "TEMPLATE_CREATED"
    TEMPLATE_UPDATED = "TEMPLATE_UPDATED"
    PREFERENCES_UPDATED = "PREFERENCES_UPDATED"






