class AuditActions:
    """
    Constants for system audit log action strings.
    """
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    USER_RESTORED = "USER_RESTORED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET = "PASSWORD_RESET"
    PROFILE_UPDATED = "PROFILE_UPDATED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    TOKEN_REFRESH = "TOKEN_REFRESH"

    # Tenant Management Audit Actions
    TENANT_CREATED = "TENANT_CREATED"
    TENANT_UPDATED = "TENANT_UPDATED"
    TENANT_SUSPENDED = "TENANT_SUSPENDED"
    TENANT_ACTIVATED = "TENANT_ACTIVATED"
    TENANT_DELETED = "TENANT_DELETED"
    TENANT_RESTORED = "TENANT_RESTORED"

    # Visitor Management Audit Actions
    VISITOR_CREATED = "VISITOR_CREATED"
    VISITOR_UPDATED = "VISITOR_UPDATED"
    VISITOR_VERIFIED = "VISITOR_VERIFIED"
    VISITOR_BLACKLISTED = "VISITOR_BLACKLISTED"
    VISITOR_BLACKLIST_REMOVED = "VISITOR_BLACKLIST_REMOVED"
    VISITOR_RESTORED = "VISITOR_RESTORED"
    VISITOR_DELETED = "VISITOR_DELETED"
    VISITOR_ACTIVATED = "VISITOR_ACTIVATED"
    VISITOR_DEACTIVATED = "VISITOR_DEACTIVATED"


