class Permissions:
    """
    Constants for system permission codes.
    """
    USER_CREATE = "USER_CREATE"
    USER_READ = "USER_READ"
    USER_UPDATE = "USER_UPDATE"
    USER_DELETE = "USER_DELETE"
    USER_RESTORE = "USER_RESTORE"
    USER_MANAGE_STATUS = "USER_MANAGE_STATUS"
    USER_RESET_PASSWORD = "USER_RESET_PASSWORD"
    
    PROFILE_VIEW = "PROFILE_VIEW"
    PROFILE_UPDATE = "PROFILE_UPDATE"

    # Visitor Permissions
    VISITOR_CREATE = "VISITOR_CREATE"
    VISITOR_READ = "VISITOR_READ"
    VISITOR_UPDATE = "VISITOR_UPDATE"
    VISITOR_DELETE = "VISITOR_DELETE"
    VISITOR_VERIFY = "VISITOR_VERIFY"
    VISITOR_BLACKLIST = "VISITOR_BLACKLIST"
    VISITOR_EXPORT = "VISITOR_EXPORT"
    VISITOR_RESTORE = "VISITOR_RESTORE"
    VISITOR_STATUS = "VISITOR_STATUS"

    # Visit Request Permissions
    VISIT_REQUEST_CREATE = "VISIT_REQUEST_CREATE"
    VISIT_REQUEST_READ = "VISIT_REQUEST_READ"
    VISIT_REQUEST_UPDATE = "VISIT_REQUEST_UPDATE"
    VISIT_REQUEST_DELETE = "VISIT_REQUEST_DELETE"
    VISIT_REQUEST_APPROVE = "VISIT_REQUEST_APPROVE"
    VISIT_REQUEST_REJECT = "VISIT_REQUEST_REJECT"
    VISIT_REQUEST_CANCEL = "VISIT_REQUEST_CANCEL"
    VISIT_REQUEST_RESTORE = "VISIT_REQUEST_RESTORE"
    VISIT_REQUEST_EXPORT = "VISIT_REQUEST_EXPORT"

    # Visitor Pass & QR Permissions
    PASS_GENERATE = "PASS_GENERATE"
    PASS_READ = "PASS_READ"
    PASS_UPDATE = "PASS_UPDATE"
    PASS_DELETE = "PASS_DELETE"
    PASS_REVOKE = "PASS_REVOKE"
    PASS_RESTORE = "PASS_RESTORE"
    PASS_EXPORT = "PASS_EXPORT"
    QR_VIEW = "QR_VIEW"
    QR_REGENERATE = "QR_REGENERATE"

    # Gate Security & Check-In Permissions
    CHECKIN_CREATE = "CHECKIN_CREATE"
    CHECKIN_READ = "CHECKIN_READ"
    CHECKIN_MANUAL = "CHECKIN_MANUAL"
    CHECKOUT_CREATE = "CHECKOUT_CREATE"
    CHECKOUT_MANUAL = "CHECKOUT_MANUAL"
    CHECKIN_UNDO = "CHECKIN_UNDO"
    CHECKIN_EXPORT = "CHECKIN_EXPORT"
    GATE_DASHBOARD_VIEW = "GATE_DASHBOARD_VIEW"
    SCAN_LOGS_VIEW = "SCAN_LOGS_VIEW"

    # Host Availability Permissions
    AVAILABILITY_CREATE = "AVAILABILITY_CREATE"
    AVAILABILITY_READ = "AVAILABILITY_READ"
    AVAILABILITY_UPDATE = "AVAILABILITY_UPDATE"
    AVAILABILITY_DELETE = "AVAILABILITY_DELETE"

    # Approval Workflow Permissions
    APPROVAL_CREATE = "APPROVAL_CREATE"
    APPROVAL_READ = "APPROVAL_READ"
    APPROVAL_ACTION = "APPROVAL_ACTION"
    APPROVAL_DELEGATE = "APPROVAL_DELEGATE"
    APPROVAL_ESCALATE = "APPROVAL_ESCALATE"

    # Notification Management Permissions
    NOTIFICATION_SEND = "NOTIFICATION_SEND"
    NOTIFICATION_READ = "NOTIFICATION_READ"
    NOTIFICATION_MANAGE_TEMPLATES = "NOTIFICATION_MANAGE_TEMPLATES"
    NOTIFICATION_PREFERENCES = "NOTIFICATION_PREFERENCES"
