class Permissions:
    """
    Constants for system permission codes.
    """
    USER_CREATE = "USER_CREATE"
    USER_READ = "USER_READ"
    USER_UPDATE = "USER_UPDATE"
    USER_DELETE = "USER_DELETE"
    USER_RESTORE = "USER_RESTORE"
    USER_MANAGE_STATUS = "USER_MANAGE_STATUS"
    USER_RESET_PASSWORD = "USER_RESET_PASSWORD"
    
    PROFILE_VIEW = "PROFILE_VIEW"
    PROFILE_UPDATE = "PROFILE_UPDATE"

    # Visitor Permissions
    VISITOR_CREATE = "VISITOR_CREATE"
    VISITOR_READ = "VISITOR_READ"
    VISITOR_UPDATE = "VISITOR_UPDATE"
    VISITOR_DELETE = "VISITOR_DELETE"
    VISITOR_VERIFY = "VISITOR_VERIFY"
    VISITOR_BLACKLIST = "VISITOR_BLACKLIST"
    VISITOR_EXPORT = "VISITOR_EXPORT"
    VISITOR_RESTORE = "VISITOR_RESTORE"
    VISITOR_STATUS = "VISITOR_STATUS"

    # Visit Request Permissions
    VISIT_REQUEST_CREATE = "VISIT_REQUEST_CREATE"
    VISIT_REQUEST_READ = "VISIT_REQUEST_READ"
    VISIT_REQUEST_UPDATE = "VISIT_REQUEST_UPDATE"
    VISIT_REQUEST_DELETE = "VISIT_REQUEST_DELETE"
    VISIT_REQUEST_APPROVE = "VISIT_REQUEST_APPROVE"
    VISIT_REQUEST_REJECT = "VISIT_REQUEST_REJECT"
    VISIT_REQUEST_CANCEL = "VISIT_REQUEST_CANCEL"
    VISIT_REQUEST_RESTORE = "VISIT_REQUEST_RESTORE"
    VISIT_REQUEST_EXPORT = "VISIT_REQUEST_EXPORT"


